server:
  port: 2801

spring:
  application:
    name: gate-way
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

#zuul:
#  routes:
#    app1:
#      path: /app1/**
#      serviceId: app1
#    app2:
#      path: /app2/**
#      serviceId: app2